package interfaces;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Admin {
    // Encapsulated attributes
    private String adminId;
    private String username;
    private String password;
    private String firstname;
    private String surname;
    private String email;
    private String department;
    private String position;
    private LocalDateTime lastLogin;

    // Static counter for generating admin IDs
    private static int adminCounter = 1;

    // Constructor
    public Admin(String username, String password, String firstname, String surname,
                 String email, String department, String position) {
        this.adminId = "ADM" + (++adminCounter);
        this.username = username;
        this.password = password;
        this.firstname = firstname;
        this.surname = surname;
        this.email = email;
        this.department = department;
        this.position = position;
    }

    // Authentication method
    public boolean authenticate(String inputPassword) {
        return this.password.equals(inputPassword);
    }

    public void recordLogin() {
        this.lastLogin = LocalDateTime.now();
        System.out.println("Admin " + username + " logged in at: " +
                lastLogin.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
    }

    // Admin-specific methods
    public void viewSystemStats(int totalCustomers, int totalAccounts, double totalBalance) {
        System.out.println("\n=== SYSTEM STATISTICS ===");
        System.out.println("Generated by: " + firstname + " " + surname + " (" + position + ")");
        System.out.println("Time: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        System.out.println("Total Customers: " + totalCustomers);
        System.out.println("Total Accounts: " + totalAccounts);
        System.out.println("Total Balance: BWP " + String.format("%.2f", totalBalance));
        System.out.println("=================================");
    }

    public void generateCustomerReport(Customer customer) {
        System.out.println("\n=== CUSTOMER REPORT ===");
        System.out.println("Customer: " + customer.getFirstname() + " " + customer.getSurname());
        System.out.println("Customer ID: " + customer.getCustomerId());
        System.out.println("Email: " + customer.getEmail());
        System.out.println("Phone: " + customer.getPhoneNumber());
        System.out.println("Address: " + customer.getAddress());
        System.out.println("Employment Status: " + (customer.isEmployed() ? "Employed" : "Not Employed"));
        if (customer.isEmployed()) {
            System.out.println("Company: " + customer.getCompanyName());
        }
        System.out.println("Number of Accounts: " + customer.getAccounts().contains());
        System.out.println("Total Balance: BWP " + String.format("%.2f", customer.getTotalBalance()));
        System.out.println("Accounts:");
        customer.displayAllAccounts();
        System.out.println("Generated by: " + firstname + " " + surname + " (" + position + ")");
        System.out.println("=========================");
    }

    // Getters and Setters
    public String getAdminId() { return adminId; }
    public String getUsername() { return username; }
    public String getFirstname() { return firstname; }
    public String getSurname() { return surname; }
    public String getEmail() { return email; }
    public String getDepartment() { return department; }
    public String getPosition() { return position; }
    public LocalDateTime getLastLogin() { return lastLogin; }

    @Override
    public String toString() {
        return "Admin{" +
                "adminId='" + adminId + '\'' +
                ", username='" + username + '\'' +
                ", firstname='" + firstname + '\'' +
                ", surname='" + surname + '\'' +
                ", email='" + email + '\'' +
                ", department='" + department + '\'' +
                ", position='" + position + '\'' +
                ", lastLogin=" + (lastLogin != null ?
                lastLogin.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) : "Never") +
                '}';
    }
}